pipeline{
    agent { 'electronix'}
    
    stages("Electronix Setup"){
        steps {echo "Hello from Electronix"}
    }

        stage("Elecronix Setup"){
            steps {echo "Electronix Setup is working✅"}
        }
    }

}